#!/usr/bin/expect

set host bandit.labs.overthewire.org
set user bandit12
set password 5Te8Y4drgCRfCx8ugdwuEX8KFC6k2EUu
spawn ssh -p 2220 $user@$host
expect "This is a OverTheWire game server."
expect "password"
send -- "$password\r"

# Level Goal
# The password for the next level is stored in the file data.txt, which is a 
# hexdump of a file that has been repeatedly compressed. For this level it may
# be useful to create a directory under /tmp in which you can work using mkdir.
# For example: mkdir /tmp/myname123. Then copy the datafile using cp, and rename
# it using mv (read the manpages!)

# checkout directory
expect "~"
send -- "ls\r"

# Man, this one was annoying. Psuedocode is as follows:
# `mktemp -d` # => make temp directory to work in
# cp data.txt to temp dir
# We know that file exists as a hexdump, so first we need to unencode it. 
# xxd -r data_copy.txt > data2.bin
# When in doubt, inspect the file using `file`: `file data2.bin
# Then, move through the motions of untarring, ungzipping, and unbzipping

# TODO: figure how to run automated extraction script, perhaps in ruby
# when all is said and done (data.bin - ASCII file), the following output is found:
# The password is 8ZjyCRiBWFYkneahHwxCv3wb2a1ORpYL

interact