#!/usr/bin/expect

set host bandit.labs.overthewire.org
set user bandit16
set password cluFn7wTiGryunymYOu4RcffSxQluehd
spawn ssh -p 2220 $user@$host
expect "This is a OverTheWire game server."
expect "password"
send -- "$password\r"

# checkout directory
expect "~"
send -- "ls\r"

interact