#!/usr/bin/expect

set host bandit.labs.overthewire.org
set user bandit10
set password truKLdjsbJ5g7yyJ2X2R0o3a5HQJFuLk
spawn ssh -p 2220 $user@$host
expect "This is a OverTheWire game server."
expect "password"
send -- "$password\r"

# Level Goal
# The password for the next level is stored in the file data.txt, which contains
 # base64 encoded data

# checkout directory
expect "~"
send -- "ls\r"

# checkout directory
expect "~"
send -- "base64 -d data.txt\r"
# > The password is IFukwKGsFW8MOq3IRFqrxE1hxTNEbUPR

interact