#!/usr/bin/expect

set host bandit.labs.overthewire.org
set user bandit15
set password BfMYroe26WYalil77FoDi9qh59eK5xNr
spawn ssh -p 2220 $user@$host
expect "This is a OverTheWire game server."
expect "password"
send -- "$password\r"

# Level Goal
# The password for the next level can be retrieved by submitting the password of
# the current level to port 30001 on localhost using SSL encryption.

# Helpful note: Getting “HEARTBEATING” and “Read R BLOCK”? Use -ign_eof and read
# the “CONNECTED COMMANDS” section in the manpage. Next to ‘R’ and ‘Q’, the ‘B’ 
# command also works in this version of that command…

# checkout directory
expect "~"
send -- "ls -a\r"

interact