#!/usr/bin/expect

set host bandit.labs.overthewire.org
set user bandit3
set password UmHadQclWmgdLOKQ3YNgjWxGoRMb5luK
spawn ssh -p 2220 $user@$host
expect "This is a OverTheWire game server."
expect "password"
send -- "$password\r"

# checkout directory
expect "~"
send -- "ls\r"

expect "~"
send -- "cd inhere/\r"

expect "~"
send -- "ls -a\r"

expect "~"
send -- "cat .hidden\r"
# > pIwrPrtPN36QITSp3EQaw936yaFoFgAB
interact