#!/usr/bin/expect

set host bandit.labs.overthewire.org
set user bandit19
set password IueksS7Ubh8G3DCwVzrTd8rAVOwq3M5x
spawn ssh -p 2220 $user@$host
expect "This is a OverTheWire game server."
expect "password"
send -- "$password\r"

# checkout directory
expect "~"
send -- "ls\r"

# Set uid allows certain executables to run specific permissions. 
# In order to access the password in bandit20 (via cat), we need to either be logged in
# as the owner (i.e. bandit20, see owners using `ls -l`) or use the executable to 
# access files owned by bandit20 (presumably)
expect "~"
send -- "./bandit20-do cat /etc/bandit_pass/bandit20\r"
# GbKksEFF4yrVs6il55v6gwY5aVje5f0j

interact