#!/usr/bin/expect

set host bandit.labs.overthewire.org
set user bandit21
set password gE269g2h3mw3pwgrj0Ha9Uoqen1c9DGr
spawn ssh -p 2220 $user@$host
expect "This is a OverTheWire game server."
expect "password"
send -- "$password\r"

# checkout directory
expect "~"
send -- "ls\r"

expect "~"
send -- "ls /etc/cron.d/ \r"

expect "~"
send -- "cat /etc/cron.d/cronjob_bandit22 \r"

expect "~"
send -- "cat /usr/bin/cronjob_bandit22.sh \r"

expect "~"
send -- "cat /tmp/t7O6lds9S0RqQh9aMcz6ShpAoZKF7fgv \r"

# Yk7owGAcWjwMVRwrTesJEwB7WVOiILLI
interact